In [36]:
import numpy as np
import matplotlib.pyplot as plt 

In [37]:
DNA_SIZE = 10
POP_SIZE = 100
CROSS_RATE = 0.8
MUTATION_RATE = 0.003
N_GENERATIONS = 100
X_BOUND = [0,5]

In [38]:
def F(x): 
    return np.sin(10*x)*x + np.cos(2*x)*x     

def get_fitness(pred): 
    return pred + 1e-3 - np.min(pred)

def translateDNA(pop):
    return pop.dot(2 ** np.arange(DNA_SIZE)[::-1]) / float(2**DNA_SIZE-1) * X_BOUND[1]

def select(pop, fitness):    # nature selection wrt pop's fitness
    idx = np.random.choice(np.arange(POP_SIZE), size=POP_SIZE, replace=True,
                           p=fitness/fitness.sum())
    return pop[idx]

def crossover(parent, pop):     # mating process (genes crossover)
    if np.random.rand() < CROSS_RATE:
        i_ = np.random.randint(0, POP_SIZE, size=1)                             # select another individual from pop
        cross_points = np.random.randint(0, 2, size=DNA_SIZE).astype(np.bool)   # choose crossover points
        parent[cross_points] = pop[i_, cross_points]                            # mating and produce one child
    return parent

def mutate(child):
    for point in range(DNA_SIZE):
        if np.random.rand() < MUTATION_RATE:
            child[point] = 1 if child[point] == 0 else 0
    return child


In [39]:
pop = np.random.randint(2, size = (POP_SIZE,DNA_SIZE)) # 初期集団（初期遺伝子）の作成
print(pop)
plt.ion()


[[1 0 1 1 1 0 0 1 1 1]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 1 1 0 0 0 1 0 1]
 [1 1 0 1 1 0 1 0 0 0]
 [1 0 1 0 1 1 1 1 0 1]
 [0 1 0 1 0 0 0 1 1 0]
 [1 1 0 1 1 1 1 0 0 1]
 [0 1 0 0 1 1 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 1 1 1 1 1]
 [0 1 0 1 1 1 1 1 0 1]
 [0 0 1 0 1 1 1 0 1 1]
 [1 1 1 0 1 0 1 1 1 0]
 [1 0 1 1 0 0 0 1 1 0]
 [1 1 1 0 1 0 1 1 0 1]
 [0 0 0 0 1 1 0 1 0 1]
 [0 1 1 1 1 1 0 1 1 0]
 [1 1 0 1 0 0 1 1 1 0]
 [1 1 0 0 1 0 1 1 1 1]
 [1 0 1 1 1 0 1 0 1 1]
 [1 0 0 1 0 0 0 1 1 1]
 [1 0 1 0 0 1 1 1 1 1]
 [0 1 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 0 0]
 [1 1 0 0 0 1 1 1 1 1]
 [1 1 1 1 0 1 0 1 1 1]
 [0 1 1 0 0 1 1 0 1 0]
 [0 1 1 0 0 0 0 1 1 0]
 [1 0 0 0 1 1 0 1 1 0]
 [0 0 0 1 0 1 0 1 0 0]
 [1 1 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 1 0 0 0]
 [1 1 1 0 0 1 1 1 1 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 0 1 1 0 1 0 1 1 0]
 [1 0 0 1 0 1 0 1 1 1]
 [1 0 1 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 0]
 [0 0 0 1 1 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [1 1 1 1 0 0 0 0 1 1]
 [1 1 1 0 1